# Generated by Django 6.0.4 on 2026-05-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("post_nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("birthday", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                (
                    "carte_identite",
                    models.ImageField(upload_to="clients/identites/%Y/%m/"),
                ),
                (
                    "photo_passeport",
                    models.ImageField(upload_to="clients/photos/%Y/%m/"),
                ),
                (
                    "numero_compte",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "devise",
                    models.CharField(
                        choices=[("USD", "Dollar Américain ($)")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("EPARGNE", "Compte Épargne"),
                            ("COURANT", "Compte Courant"),
                            ("SALAIRE", "Compte Salaire"),
                        ],
                        default="EPARGNE",
                        max_length=10,
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Le client définira son mot de passe lors de la première connexion",
                        max_length=128,
                        verbose_name="Mot de passe",
                    ),
                ),
                (
                    "password_is_set",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le client a déjà défini son mot de passe",
                        verbose_name="Mot de passe défini",
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("INACTIF", "Inactif"),
                            ("ACTIF", "Actif"),
                            ("BLOQUE", "Bloqué"),
                            ("CLOTURE", "Clôturé"),
                        ],
                        default="INACTIF",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["numero_compte"], name="clients_cli_numero__a5e369_idx"
                    ),
                    models.Index(fields=["email"], name="clients_cli_email_56b9fc_idx"),
                    models.Index(
                        fields=["statut"], name="clients_cli_statut_d69dca_idx"
                    ),
                ],
            },
        ),
    ]
