# Generated by Django 6.0.4 on 2026-05-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Succès"),
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                        ],
                        default="INFO",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                ],
            },
        ),
    ]
