# Generated by Django 6.0.4 on 2026-05-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[("DEPOT", "Dépôt"), ("RETRAIT", "Retrait")],
                        max_length=10,
                        verbose_name="Type de transaction",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("REUSSIE", "Réussie"),
                            ("ECHOUEE", "Échouée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="REUSSIE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "ancien_solde",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Ancien solde"
                    ),
                ),
                (
                    "nouveau_solde",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Nouveau solde"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de transaction"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_effectuees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference"], name="transaction_referen_923a88_idx"
                    ),
                    models.Index(
                        fields=["client", "-created_at"],
                        name="transaction_client__df59fd_idx",
                    ),
                    models.Index(
                        fields=["type_transaction"],
                        name="transaction_type_tr_80de78_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="transaction_created_67ce7b_idx"
                    ),
                ],
            },
        ),
    ]
