# Generated by Django 6.0.4 on 2026-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type_transaction",
            field=models.CharField(
                choices=[
                    ("DEPOT", "Dépôt"),
                    ("RETRAIT", "Retrait"),
                    ("TRANSFERT", "Transfert"),
                ],
                max_length=10,
                verbose_name="Type de transaction",
            ),
        ),
    ]
